MAX_SAFE_INTEGER = 9007199254740991  # Ensure compatibility with JavaScript

MAX_SAFE_DECIMAL = 9007199254740991.0  # Ensure compatibility with JavaScript


DEFAULT_IMAGE_FORMAT = "PNG"

DEFAULT_IMAGE_MIME_TYPE = "image/png"

REGIONAL_PROMPT_ADVANCED_FIELD_ALIAS = "regional_prompt"

PROMPT_FIELD_ALIAS = "prompt"

NEGATIVE_PROMPT_FIELD_ALIAS = "negative_prompt"

INFLUENCE_FIELD_ALIAS = "influence"

INFLUENCE_FIELD_DEFAULT = 1.0

CONTROLS_FIELD_ALIAS = "controls"

SAFE_DEFAULT_FIELD_KEY = "_default"

REAL_DEFAULT_FIELD_KEY = "default"
